resolver: ./snapshot.yaml
compiler: ghc-8.6.5

allow-newer: true

packages:
  - explorer-api
  - rest-common
  - submit-api

extra-deps:
  - git: https://github.com/input-output-hk/cardano-db-sync
    commit: eb58508e3fe182976f1d5d69a1fdc8f393029eaf
    subdirs:
      - cardano-db
      - cardano-db-sync

  - git: https://github.com/input-output-hk/cardano-crypto
    commit: 2547ad1e80aeabca2899951601079408becbc92c

ghc-options:
  cardano-explorer-api: -Wall -Werror -fwarn-redundant-constraints
  cardano-submit-api:   -Wall -Werror -fwarn-redundant-constraints

nix:
  shell-file: nix/stack-shell.nix

flags:
  # Bundle VRF crypto in libsodium and do not rely on an external fork to have it.
  # This still requires the host system to have the 'standard' libsodium installed.
  cardano-crypto-praos:
    external-libsodium-vrf: false

# generate files required by weeder.
# see https://github.com/ndmitchell/weeder/issues/53
ghc-options: {"$locals": -ddump-to-file -ddump-hi}
